Feat/rls
molgenis/molgenis-tools-commander pull request #172
Opened 2020-11-02 08:30 UTC by tommydeboer

#### Checklist
- [ ] Functionality works & meets specifications
- [ ] Code reviewed
- [ ] Code unit/system tested
- [ ] User documentation updated
- [ ] Clean commits
- [ ] Added Feature/Fix to release notes

2020-11-03 11:35 UTC, tommydeboer commented
![](https://github.trello.services/images/mini-trello-icon.png) [Give RLS permissions in commander](https://trello.com/c/GQoZmAd5/534-give-rls-permissions-in-commander)

2020-11-10 09:53 UTC, fdlk requested changes
Can we take a look at this together?

2020-11-10 09:53 UTC, fdlk commented on mcmd/commands/give.py
> +
Isn't that a bug that we should fix in molgenis?

2020-11-10 09:53 UTC, fdlk commented on mcmd/molgenis/security/permission_manager.py
> +    data = {'radio-' + entity_type_id: permission.value}
I'd expect all permission assignments to go through the permission API for servers that support it.

2020-11-10 09:53 UTC, fdlk commented on tests/integration/permission_client.py
> +                                                                            principal)),
It's hard to decide what to trust and what not when writing these tests. This feels like it should be trusted code in the permissions api client, used in integration tests. Then in unit tests you could verify that the implementation calls the right endpoints.

2020-11-10 09:53 UTC, fdlk commented on mcmd/molgenis/api.py
> +@endpoint
not completely sure how the @version annotation works but I'd expect one here

2020-11-16 12:10 UTC, fdlk approved these changes

2020-11-16 12:15 UTC, merged